name: flix_id
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  awesome_snackbar_content: ^0.1.4
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  get_storage: ^2.1.1
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.1.2
  path: ^1.9.0
  riverpod_annotation: ^2.3.5
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
